#!/usr/bin/env bash
set -euo pipefail

_KERNEL="$1"
INITRD="$2"

ESP="$(bootctl --print-esp-path)"
ARCH="$(bootctl status --no-pager 2> /dev/null | awk -F: '$1~/^\s*Firmware Arch$/{print $2}' | xargs echo -n)"
MACHINE_ID="$(cat /etc/machine-id)"
source /etc/os-release

options=()
function append_options() {
	if [[ -f "$1" ]]; then
		readarray -t -d ' ' -O "${#options[@]}" options < <(cat "$1" | xargs echo -n)
	fi
}
append_options /etc/kernel/cmdline
if [[ -d /etc/cmdline.d ]]; then
	for f in /etc/cmdline.d/*.conf; do
		append_options "$f"
	done
fi

KEY="${ID}-${MKINITCPIO_PROCESS_PRESET}"
ENTRY="${ESP}/loader/entries/${KEY}.conf"

mkdir --parents "$(dirname "$ENTRY")"
cat > "$ENTRY" <<-EOF
	sort-key ${KEY}
	title ${PRETTY_NAME}
	machine-id ${MACHINE_ID}

	architecture ${ARCH}
	version ${KERNELVERSION}
	linux ${KERNELDESTINATION#"$ESP"}
	initrd ${INITRD#"$ESP"}
	options ${options[@]}
EOF

echo "Generated systemd-boot entry '${KEY}'"
